// ..\dev-a\assets\enems0.h
// Generated by eneexp3c.exe v0.1 [20170405]
// Copyleft 2016 The Mojon Twins

// Enems structure is {T YX1 YX2 P} x 3 x MAP_W x MAP_H
// y coordinates are adjusted by 1 positions

const unsigned char enems_0_00 [] = {
	0x10, 0xbe, 0xb8, 0x01, 0
};

const unsigned char enems_0_01 [] = {
	0x10, 0x9c, 0x93, 0x01, 0
};

const unsigned char enems_0_04 [] = {
	0x12, 0x7a, 0xb1, 0x02, 0
};

const unsigned char enems_0_05 [] = {
	0x10, 0x86, 0xb6, 0x02, 0x11, 0x7c, 0xbc, 0x02, 0
};

const unsigned char enems_0_06 [] = {
	0x11, 0x89, 0xb9, 0x02, 0x12, 0x53, 0xb3, 0x02, 0
};

const unsigned char * const enems_0 [] = {
	enems_0_00, enems_0_01, 0, 0, enems_0_04, enems_0_05, enems_0_06, 0
};

// Bytes: 49 vs. MAP_WxMAP_Hx12 = 96 (51%)

#define MAX_ENEMS_0_TYPE_10	7

// Hotspots structure is {T YX} x MAP_W x MAP_H
const unsigned char hotspots_0 [] = {
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x03, 0x4A, 
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01, 0x9B
};

#define MAX_HOTSPOTS_0_TYPE_0	6
#define MAX_HOTSPOTS_0_TYPE_1	1
#define MAX_HOTSPOTS_0_TYPE_3	1
