;this file for FamiTone2 library generated by text2data tool

music_b_music_data:
	.byte 4
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,307,256
	.word @song1ch0,@song1ch1,@song1ch2,@song1ch3,@song1ch4,307,256
	.word @song2ch0,@song2ch1,@song2ch2,@song2ch3,@song2ch4,307,256
	.word @song3ch0,@song3ch1,@song3ch2,@song3ch3,@song3ch4,307,256

@instruments:
	.byte $30 ;instrument $00
	.word @env1,@env0,@env0
	.byte $00
	.byte $30 ;instrument $04
	.word @env3,@env8,@env0
	.byte $00
	.byte $30 ;instrument $05
	.word @env7,@env0,@env0
	.byte $00
	.byte $30 ;instrument $06
	.word @env5,@env0,@env0
	.byte $00
	.byte $30 ;instrument $0b
	.word @env2,@env8,@env0
	.byte $00
	.byte $30 ;instrument $0c
	.word @env6,@env0,@env0
	.byte $00
	.byte $30 ;instrument $0d
	.word @env4,@env0,@env0
	.byte $00

@samples:
@env0:
	.byte $c0,$00,$00
@env1:
	.byte $cc,$00,$00
@env2:
	.byte $cd,$cb,$c9,$c8,$c5,$c3,$c1,$c0,$00,$07
@env3:
	.byte $cf,$cd,$cb,$c9,$c7,$c5,$c3,$c1,$c0,$00,$08
@env4:
	.byte $c7,$c2,$c0,$00,$02
@env5:
	.byte $ca,$c5,$c3,$c2,$c0,$00,$04
@env6:
	.byte $cc,$ca,$c8,$c6,$c4,$c3,$c2,$c1,$c0,$00,$08
@env7:
	.byte $cd,$cc,$ca,$c9,$c7,$c6,$c5,$c3,$c0,$00,$08
@env8:
	.byte $c7,$c3,$c0,$bd,$00,$02


@song0ch0:
	.byte $fb,$06
@song0ch0loop:
@ref0:
	.byte $bf
@ref1:
	.byte $bf
@ref2:
	.byte $bf
@ref3:
	.byte $bf
@ref4:
	.byte $bf
@ref5:
	.byte $bf
@ref6:
	.byte $bf
@ref7:
	.byte $bf
	.byte $fd
	.word @song0ch0loop

@song0ch1:
@song0ch1loop:
@ref8:
	.byte $bf
@ref9:
	.byte $bf
@ref10:
	.byte $bf
@ref11:
	.byte $bf
@ref12:
	.byte $bf
@ref13:
	.byte $bf
@ref14:
	.byte $bf
@ref15:
	.byte $bf
	.byte $fd
	.word @song0ch1loop

@song0ch2:
@song0ch2loop:
@ref16:
	.byte $80,$4a,$01,$01,$00,$52,$00,$56,$00,$5a,$00,$5e,$01,$01,$00,$52
	.byte $00,$4e,$01,$01,$00,$4a,$00,$4e,$00,$56,$00
@ref17:
	.byte $52,$01,$01,$00,$52,$00,$4e,$00,$4a,$00,$5a,$00,$56,$00,$52,$01
	.byte $01,$01,$01,$01,$00,$4a,$00,$4e,$00
@ref18:
	.byte $4a,$01,$01,$01,$01,$00,$4a,$00,$4e,$00,$52,$00,$56,$01,$01,$01
	.byte $01,$00,$4a,$00,$54,$00,$52,$00
@ref19:
	.byte $56,$00,$5a,$00,$5e,$01,$01,$00,$4a,$00,$5a,$00,$56,$00,$5a,$01
	.byte $01,$00,$4e,$00,$4a,$01,$00,$4e,$01,$00
@ref20:
	.byte $4a,$01,$01,$01,$01,$00,$52,$00,$4e,$01,$00,$56,$01,$01,$01,$01
	.byte $00,$5a,$00,$56,$01,$00
@ref21:
	.byte $5e,$01,$01,$01,$01,$00,$62,$00,$5e,$00,$5a,$00,$56,$00,$52,$00
	.byte $4e,$00,$4a,$00,$56,$00,$5a,$00,$62,$00,$66,$00
@ref22:
	.byte $4a,$01,$01,$01,$01,$00,$52,$00,$4e,$00,$56,$00,$5a,$01,$01,$01
	.byte $01,$00,$5e,$00,$62,$00,$66,$00
@ref23:
	.byte $6a,$01,$01,$01,$01,$00,$5e,$00,$62,$00,$5a,$00,$66,$00,$56,$00
	.byte $6a,$01,$01,$00,$52,$00,$4e,$00,$4a,$00
	.byte $fd
	.word @song0ch2loop

@song0ch3:
@song0ch3loop:
@ref24:
	.byte $84,$21,$21,$82,$0f,$84,$21,$21,$21,$82,$0f,$84,$21,$21,$21,$82
	.byte $0f,$84,$21,$21,$21,$82,$0f,$84,$20,$81
@ref25:
	.byte $21,$21,$82,$0f,$84,$21,$21,$21,$82,$0f,$84,$21,$21,$21,$82,$0f
	.byte $84,$21,$21,$21,$82,$0f,$84,$20,$81
	.byte $ff,$11
	.word @ref25
	.byte $ff,$11
	.word @ref25
	.byte $ff,$11
	.word @ref25
	.byte $ff,$11
	.word @ref25
	.byte $ff,$11
	.word @ref25
	.byte $ff,$11
	.word @ref25
	.byte $fd
	.word @song0ch3loop

@song0ch4:
@song0ch4loop:
@ref32:
	.byte $bf
@ref33:
	.byte $bf
@ref34:
	.byte $bf
@ref35:
	.byte $bf
@ref36:
	.byte $bf
@ref37:
	.byte $bf
@ref38:
	.byte $bf
@ref39:
	.byte $bf
	.byte $fd
	.word @song0ch4loop


@song1ch0:
	.byte $fb,$06
@song1ch0loop:
@ref40:
	.byte $f9,$85
@ref41:
	.byte $f9,$85
@ref42:
	.byte $f9,$85
@ref43:
	.byte $f9,$85
@ref44:
	.byte $f9,$85
@ref45:
	.byte $f9,$85
@ref46:
	.byte $f9,$85
@ref47:
	.byte $f9,$85
@ref48:
	.byte $f9,$85
@ref49:
	.byte $f9,$85
@ref50:
	.byte $f9,$85
@ref51:
	.byte $f9,$85
	.byte $fd
	.word @song1ch0loop

@song1ch1:
@song1ch1loop:
@ref52:
	.byte $f9,$85
@ref53:
	.byte $f9,$85
@ref54:
	.byte $f9,$85
@ref55:
	.byte $f9,$85
@ref56:
	.byte $f9,$85
@ref57:
	.byte $f9,$85
@ref58:
	.byte $f9,$85
@ref59:
	.byte $f9,$85
@ref60:
	.byte $f9,$85
@ref61:
	.byte $f9,$85
@ref62:
	.byte $f9,$85
@ref63:
	.byte $f9,$85
	.byte $fd
	.word @song1ch1loop

@song1ch2:
@song1ch2loop:
@ref64:
	.byte $80,$52,$83,$00,$60,$8b,$00,$5c,$58,$56,$5c,$58,$83,$00,$52,$8b
	.byte $00,$4e,$85,$4a,$83,$00,$62,$89,$01,$60,$5c,$58,$60,$5c,$99,$00
	.byte $81
@ref65:
	.byte $52,$83,$00,$60,$89,$01,$5c,$58,$56,$5c,$58,$83,$00,$52,$89,$01
	.byte $4e,$83,$00,$4b,$01,$4b,$01,$4e,$00,$4f,$01,$52,$99,$00,$85
@ref66:
	.byte $52,$83,$00,$60,$8b,$00,$5c,$58,$56,$5c,$58,$83,$00,$52,$8b,$00
	.byte $4e,$85,$4a,$83,$00,$62,$89,$01,$60,$5c,$58,$60,$5c,$99,$00,$81
	.byte $ff,$1f
	.word @ref65
@ref68:
	.byte $56,$89,$01,$56,$83,$00,$5c,$83,$00,$59,$57,$59,$5d,$60,$89,$01
	.byte $62,$85,$01,$63,$60,$85,$5c,$85,$60,$9d
@ref69:
	.byte $56,$85,$01,$57,$58,$83,$00,$5c,$85,$58,$83,$00,$56,$83,$00,$52
	.byte $89,$01,$4a,$87,$00,$56,$87,$00,$5c,$83,$00,$60,$91,$62,$00,$60
	.byte $83,$00
	.byte $ff,$20
	.word @ref66
	.byte $ff,$1f
	.word @ref65
	.byte $ff,$20
	.word @ref66
	.byte $ff,$1f
	.word @ref65
@ref74:
	.byte $56,$87,$00,$53,$4e,$83,$00,$5c,$83,$00,$60,$87,$00,$5d,$58,$83
	.byte $00,$60,$83,$00,$62,$83,$00,$60,$83,$00,$5c,$83,$00,$62,$83,$00
	.byte $60,$99,$00,$81
@ref75:
	.byte $62,$00,$62,$62,$66,$00,$62,$00,$60,$83,$00,$58,$85,$56,$00,$56
	.byte $56,$58,$00,$5c,$00,$58,$83,$00,$53,$4f,$62,$95,$4b,$63,$60,$95
	.byte $48,$85
	.byte $fd
	.word @song1ch2loop

@song1ch3:
@song1ch3loop:
@ref76:
	.byte $8a,$21,$8c,$16,$16,$88,$0f,$8c,$16,$16,$8a,$21,$8c,$16,$16,$88
	.byte $0f,$8c,$16,$16,$8a,$21,$8c,$16,$16,$88,$0f,$8c,$16,$16,$8a,$21
	.byte $88,$0f,$0f,$8c,$16,$16,$8a,$21,$8c,$16,$16,$88,$0f,$8c,$16,$16
	.byte $8a,$21,$8c,$16,$16,$88,$0f,$8c,$16,$16,$8a,$21,$8c,$16,$16,$88
	.byte $0f,$8c,$16,$16,$8a,$21,$88,$0f,$0f,$0e,$0e
	.byte $ff,$2e
	.word @ref76
	.byte $ff,$2e
	.word @ref76
	.byte $ff,$2e
	.word @ref76
	.byte $ff,$2e
	.word @ref76
	.byte $ff,$2e
	.word @ref76
	.byte $ff,$2e
	.word @ref76
	.byte $ff,$2e
	.word @ref76
	.byte $ff,$2e
	.word @ref76
	.byte $ff,$2e
	.word @ref76
	.byte $ff,$2e
	.word @ref76
	.byte $ff,$2e
	.word @ref76
	.byte $fd
	.word @song1ch3loop

@song1ch4:
@song1ch4loop:
@ref88:
	.byte $f9,$85
@ref89:
	.byte $f9,$85
@ref90:
	.byte $f9,$85
@ref91:
	.byte $f9,$85
@ref92:
	.byte $f9,$85
@ref93:
	.byte $f9,$85
@ref94:
	.byte $f9,$85
@ref95:
	.byte $f9,$85
@ref96:
	.byte $f9,$85
@ref97:
	.byte $f9,$85
@ref98:
	.byte $f9,$85
@ref99:
	.byte $f9,$85
	.byte $fd
	.word @song1ch4loop


@song2ch0:
	.byte $fb,$06
@song2ch0loop:
@ref100:
	.byte $f9,$85
@ref101:
	.byte $f9,$85
@ref102:
	.byte $f9,$85
@ref103:
	.byte $f9,$85
@ref104:
	.byte $f9,$85
@ref105:
	.byte $f9,$85
@ref106:
	.byte $f9,$85
@ref107:
	.byte $f9,$85
@ref108:
	.byte $f9,$85
@ref109:
	.byte $f9,$85
@ref110:
	.byte $f9,$85
@ref111:
	.byte $f9,$85
@ref112:
	.byte $f9,$85
	.byte $fd
	.word @song2ch0loop

@song2ch1:
@song2ch1loop:
@ref113:
	.byte $f9,$85
@ref114:
	.byte $f9,$85
@ref115:
	.byte $f9,$85
@ref116:
	.byte $f9,$85
@ref117:
	.byte $f9,$85
@ref118:
	.byte $f9,$85
@ref119:
	.byte $f9,$85
@ref120:
	.byte $f9,$85
@ref121:
	.byte $f9,$85
@ref122:
	.byte $f9,$85
@ref123:
	.byte $f9,$85
@ref124:
	.byte $f9,$85
@ref125:
	.byte $f9,$85
	.byte $fd
	.word @song2ch1loop

@song2ch2:
@song2ch2loop:
@ref126:
	.byte $00,$f9,$83
@ref127:
	.byte $80,$52,$85,$01,$48,$85,$56,$00,$57,$59,$56,$85,$01,$4e,$85,$01
	.byte $49,$01,$58,$85,$01,$4e,$00,$5d,$01,$5d,$61,$5c,$89,$01,$59,$57
	.byte $53,$4e,$81
@ref128:
	.byte $52,$85,$01,$48,$85,$01,$59,$01,$56,$85,$01,$5d,$57,$01,$4f,$01
	.byte $48,$85,$01,$56,$83,$00,$57,$58,$85,$56,$91,$5d,$53,$4e,$81
@ref129:
	.byte $52,$85,$01,$48,$85,$56,$00,$57,$59,$56,$85,$01,$4e,$85,$01,$49
	.byte $01,$58,$85,$01,$4e,$00,$5d,$01,$5d,$61,$5c,$89,$01,$59,$57,$53
	.byte $4e,$81
@ref130:
	.byte $52,$85,$01,$48,$85,$01,$59,$01,$56,$85,$01,$5d,$57,$01,$4f,$01
	.byte $48,$85,$01,$56,$83,$00,$57,$58,$85,$5c,$91,$5d,$61,$5c,$81
@ref131:
	.byte $58,$8d,$01,$41,$49,$59,$5c,$8d,$01,$61,$5d,$57,$58,$83,$40,$4e
	.byte $83,$36,$48,$83,$36,$40,$83,$36,$5c,$91,$59,$61,$5c,$81
@ref132:
	.byte $60,$8d,$01,$61,$63,$66,$00,$66,$85,$5c,$85,$56,$85,$66,$85,$6a
	.byte $85,$60,$85,$58,$85,$6a,$85,$66,$9d
@ref133:
	.byte $60,$8d,$01,$61,$63,$61,$5c,$85,$56,$85,$4e,$85,$5c,$85,$58,$85
	.byte $52,$85,$48,$85,$58,$85,$56,$9d
	.byte $ff,$22
	.word @ref129
	.byte $ff,$1f
	.word @ref128
	.byte $ff,$22
	.word @ref129
	.byte $ff,$1f
	.word @ref130
@ref138:
	.byte $3a,$b1,$3b,$52,$00,$53,$84,$3a,$bd
	.byte $fd
	.word @song2ch2loop

@song2ch3:
@song2ch3loop:
@ref139:
	.byte $84,$20,$89,$20,$85,$82,$13,$0f,$0b,$84,$20,$89,$20,$85,$82,$13
	.byte $0f,$0b,$84,$20,$89,$20,$85,$82,$13,$0f,$0b,$84,$20,$89,$20,$85
	.byte $82,$13,$0f,$0a,$81
	.byte $ff,$1d
	.word @ref139
	.byte $ff,$1d
	.word @ref139
@ref142:
	.byte $84,$21,$86,$16,$12,$82,$0b,$16,$84,$0a,$21,$86,$16,$12,$82,$0b
	.byte $16,$84,$0a,$21,$86,$16,$12,$82,$0b,$16,$84,$0a,$21,$86,$16,$12
	.byte $82,$0b,$16,$84,$0a,$21,$86,$16,$12,$82,$0b,$16,$84,$0a,$21,$86
	.byte $16,$12,$82,$0b,$16,$84,$0a,$20,$89,$20,$85,$82,$13,$0f,$0a,$81
	.byte $ff,$2c
	.word @ref142
	.byte $ff,$1d
	.word @ref139
	.byte $ff,$2c
	.word @ref142
	.byte $ff,$2c
	.word @ref142
	.byte $ff,$2c
	.word @ref142
	.byte $ff,$2c
	.word @ref142
	.byte $ff,$2c
	.word @ref142
	.byte $ff,$2c
	.word @ref142
	.byte $ff,$1d
	.word @ref139
	.byte $fd
	.word @song2ch3loop

@song2ch4:
@song2ch4loop:
@ref152:
	.byte $f9,$85
@ref153:
	.byte $f9,$85
@ref154:
	.byte $f9,$85
@ref155:
	.byte $f9,$85
@ref156:
	.byte $f9,$85
@ref157:
	.byte $f9,$85
@ref158:
	.byte $f9,$85
@ref159:
	.byte $f9,$85
@ref160:
	.byte $f9,$85
@ref161:
	.byte $f9,$85
@ref162:
	.byte $f9,$85
@ref163:
	.byte $f9,$85
@ref164:
	.byte $f9,$85
	.byte $fd
	.word @song2ch4loop


@song3ch0:
	.byte $fb,$06
@song3ch0loop:
@ref165:
	.byte $bf
@ref166:
	.byte $bf
@ref167:
	.byte $bf
@ref168:
	.byte $bf
@ref169:
	.byte $bf
@ref170:
	.byte $bf
@ref171:
	.byte $bf
@ref172:
	.byte $bf
@ref173:
	.byte $bf
@ref174:
	.byte $bf
@ref175:
	.byte $bf
@ref176:
	.byte $bf
@ref177:
	.byte $bf
@ref178:
	.byte $bf
@ref179:
	.byte $bf
@ref180:
	.byte $bf
@ref181:
	.byte $bf
@ref182:
	.byte $bf
@ref183:
	.byte $bf
@ref184:
	.byte $bf
@ref185:
	.byte $bf
@ref186:
	.byte $bf
@ref187:
	.byte $bf
@ref188:
	.byte $bf
	.byte $fd
	.word @song3ch0loop

@song3ch1:
@song3ch1loop:
@ref189:
	.byte $bf
@ref190:
	.byte $bf
@ref191:
	.byte $bf
@ref192:
	.byte $bf
@ref193:
	.byte $bf
@ref194:
	.byte $bf
@ref195:
	.byte $bf
@ref196:
	.byte $bf
@ref197:
	.byte $bf
@ref198:
	.byte $bf
@ref199:
	.byte $bf
@ref200:
	.byte $bf
@ref201:
	.byte $bf
@ref202:
	.byte $bf
@ref203:
	.byte $bf
@ref204:
	.byte $bf
@ref205:
	.byte $bf
@ref206:
	.byte $bf
@ref207:
	.byte $bf
@ref208:
	.byte $bf
@ref209:
	.byte $bf
@ref210:
	.byte $bf
@ref211:
	.byte $bf
@ref212:
	.byte $bf
	.byte $fd
	.word @song3ch1loop

@song3ch2:
@song3ch2loop:
@ref213:
	.byte $80,$4a,$85,$01,$51,$58,$85,$00,$85,$4a,$00,$4a,$00,$4b,$5b,$59
	.byte $01,$55,$50,$00
@ref214:
	.byte $54,$85,$01,$51,$4f,$01,$59,$5b,$59,$01,$55,$01,$51,$01,$4f,$00
	.byte $81
@ref215:
	.byte $4a,$85,$01,$51,$58,$85,$00,$85,$4a,$00,$4a,$00,$4b,$5b,$59,$01
	.byte $54,$00,$50,$00
@ref216:
	.byte $54,$85,$01,$51,$4f,$01,$51,$4f,$4a,$91,$40,$00,$40,$00,$40,$00
@ref217:
	.byte $4a,$85,$01,$51,$58,$85,$00,$85,$4a,$00,$4a,$00,$4b,$5b,$59,$01
	.byte $55,$50,$00
	.byte $ff,$11
	.word @ref214
	.byte $ff,$14
	.word @ref215
@ref220:
	.byte $54,$85,$01,$51,$4f,$01,$51,$4f,$4a,$99,$4a,$81
@ref221:
	.byte $4e,$85,$01,$4e,$00,$4f,$01,$4f,$55,$51,$01,$4f,$01,$4b,$01,$4a
	.byte $46,$42,$40
@ref222:
	.byte $3d,$01,$5a,$89,$01,$59,$55,$58,$95,$01,$4a,$81
@ref223:
	.byte $4e,$85,$01,$51,$54,$85,$51,$4f,$51,$01,$55,$01,$59,$01,$4f,$4a
	.byte $81
@ref224:
	.byte $4e,$91,$01,$51,$4f,$4a,$91,$40,$00,$40,$00,$40,$00
	.byte $ff,$13
	.word @ref217
	.byte $ff,$11
	.word @ref214
	.byte $ff,$14
	.word @ref215
	.byte $ff,$10
	.word @ref216
	.byte $ff,$13
	.word @ref217
	.byte $ff,$11
	.word @ref214
	.byte $ff,$14
	.word @ref215
	.byte $ff,$0c
	.word @ref220
@ref233:
	.byte $54,$85,$01,$55,$59,$01,$5b,$01,$5a,$85,$01,$58,$00,$58,$89,$00
	.byte $81
@ref234:
	.byte $54,$85,$01,$55,$59,$01,$5b,$01,$58,$9d
@ref235:
	.byte $54,$85,$01,$55,$59,$01,$5a,$85,$59,$01,$5b,$01,$5e,$89,$00,$81
@ref236:
	.byte $62,$00,$5f,$01,$5b,$59,$01,$55,$01,$50,$91,$5e,$62,$5e,$00,$40
	.byte $81
	.byte $fd
	.word @song3ch2loop

@song3ch3:
@song3ch3loop:
@ref237:
	.byte $84,$20,$89,$21,$82,$16,$8d,$13,$12,$85,$84,$21,$82,$12,$85,$86
	.byte $17,$16,$81
@ref238:
	.byte $84,$21,$86,$16,$16,$82,$17,$86,$16,$16,$84,$21,$86,$16,$16,$82
	.byte $17,$86,$16,$16,$84,$21,$86,$17,$84,$21,$86,$17,$84,$21,$86,$17
	.byte $82,$17,$16,$16
@ref239:
	.byte $84,$21,$86,$16,$16,$82,$17,$86,$16,$16,$84,$21,$86,$16,$16,$82
	.byte $17,$86,$16,$16,$84,$21,$86,$16,$16,$82,$17,$86,$16,$16,$84,$21
	.byte $86,$16,$16,$82,$17,$86,$16,$16
	.byte $ff,$15
	.word @ref238
	.byte $ff,$18
	.word @ref239
	.byte $ff,$15
	.word @ref238
	.byte $ff,$18
	.word @ref239
	.byte $ff,$15
	.word @ref238
	.byte $ff,$18
	.word @ref239
	.byte $ff,$15
	.word @ref238
	.byte $ff,$18
	.word @ref239
	.byte $ff,$15
	.word @ref238
	.byte $ff,$0e
	.word @ref237
	.byte $ff,$15
	.word @ref238
	.byte $ff,$18
	.word @ref239
	.byte $ff,$15
	.word @ref238
	.byte $ff,$18
	.word @ref239
	.byte $ff,$15
	.word @ref238
	.byte $ff,$18
	.word @ref239
	.byte $ff,$15
	.word @ref238
	.byte $ff,$18
	.word @ref239
	.byte $ff,$15
	.word @ref238
	.byte $ff,$18
	.word @ref239
	.byte $ff,$15
	.word @ref238
	.byte $fd
	.word @song3ch3loop

@song3ch4:
@song3ch4loop:
@ref261:
	.byte $bf
@ref262:
	.byte $bf
@ref263:
	.byte $bf
@ref264:
	.byte $bf
@ref265:
	.byte $bf
@ref266:
	.byte $bf
@ref267:
	.byte $bf
@ref268:
	.byte $bf
@ref269:
	.byte $bf
@ref270:
	.byte $bf
@ref271:
	.byte $bf
@ref272:
	.byte $bf
@ref273:
	.byte $bf
@ref274:
	.byte $bf
@ref275:
	.byte $bf
@ref276:
	.byte $bf
@ref277:
	.byte $bf
@ref278:
	.byte $bf
@ref279:
	.byte $bf
@ref280:
	.byte $bf
@ref281:
	.byte $bf
@ref282:
	.byte $bf
@ref283:
	.byte $bf
@ref284:
	.byte $bf
	.byte $fd
	.word @song3ch4loop
