// ..\dev-b\assets\enems6.h
// Generated by eneexp3c.exe v0.1 [20170405]
// Copyleft 2016 The Mojon Twins

// Enems structure is {T YX1 YX2 P} x 3 x MAP_W x MAP_H
// y coordinates are adjusted by 1 positions

const unsigned char enems_6_01 [] = {
	0xf0, 0x32, 0x42, 0x00, 0
};

const unsigned char * const enems_6 [] = {
	0, enems_6_01, 0
};

// Bytes: 11 vs. MAP_WxMAP_Hx12 = 36 (30%)

#define MAX_ENEMS_6_TYPE_F0	1

// Hotspots structure is {T YX} x MAP_W x MAP_H
const unsigned char hotspots_6 [] = {
	0x04, 0x37, 0x03, 0xBC, 0x03, 0x92};

#define MAX_HOTSPOTS_6_TYPE_3	2
#define MAX_HOTSPOTS_6_TYPE_4	1
